---
apiVersion: "schemaregistry.jikkou.io/v1beta2"
kind: "SchemaRegistrySubject"
metadata:
  name: "PersonAvro"
  labels: {} 
  annotations:
    schemaregistry.jikkou.io/normalize-schema: true
spec:
#  compatibilityLevel: "FULL_TRANSITIVE"
  schemaType: "AVRO"
  schema:
    $ref: {{ resource.directoryPath }}/avro-schema.avsc
