= Jikkou : Automate the management of your Apache Kafka using GitOps approach!

image:https://img.shields.io/github/license/streamthoughts/jikkou[]
image:https://img.shields.io/github/issues/streamthoughts/jikkou[]
image:https://img.shields.io/github/forks/streamthoughts/jikkou[]
image:https://img.shields.io/github/stars/streamthoughts/jikkou[]
image:https://github.com/streamthoughts/jikkou/actions/workflows/gradle-build.yml/badge.svg[]

toc::[]

__Note: Jikkou is the project formerly known as **Kafka Specs**. Old versions of this project can still be found under that name.__

**Jikkou** (jikkō / 実行) is a command-line tool to help you automate the management of the configurations that live on your http://kafka.apache.org/[Apache Kafka] clusters.

It allows you to define the desired current state of your **Topics**, **ACLs**, or **Quotas**, using one or more YAML specification files (called _kafka-specs_ files):

topics-specs.yml:::
[source,yaml]
----
version: 1
specs:
  topics:
  - name: 'my-first-topic-with-jikkou'
    partitions: 12
    replication_factor: 3
    configs:
      min.insync.replicas: 2
----

It will then take care of computing and applying the necessary changes directly to your cluster.

[source, bash]
----
$ jikkou --bootstrap-servers localhost:9092 topics apply \
    --file-path topics-specs.yml \
    --yes
----

[source]
----
TASK [CREATE] Create a new topic my-first-topic-with-jikkou (partitions=12, replicas=3) - CHANGED **********************
----
[source, json]
----
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "my-first-topic-with-jikkou",
    "operation" : "ADD",
    "partitions" : {
      "after" : 12,
      "operation" : "ADD"
    },
    "replication_factor" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
----
[source]
----
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

Most of the time, you will use Jikkou part of your CI/CD pipeline allowing you to version and ship your Apache Kafka resources directly from Git (more on https://about.gitlab.com/topics/gitops/[GitOps])

Jikkou can be used with self-hosted Kafka, managed Kafka and Confluent Cloud.

== Why ?

We initially started this project to allow us to quickly and easily (re)create Kafka topics in a declarative way on ephemeral Kafka clusters that we used only for integration testing purposes.

Over time, we began to refactor the solution and extend its functionality to support more production contexts and allow developers and operations teams to share a common tool for working on Kafka.

== Requirements :

1. Kafka 1.0.0 ...
2. Java 11+

_Note: Internally, Jikkou uses the Kafka Java Admin Client API._ Depending on the Kafka Cluster version you use all features may not be supported.

== Usages

[source,bash]
----
$ docker run -it streamthoughts/jikkou:latest --help
Usage:
Jikkou [-hV] [--bootstrap-servers=<bootstrapServer>] [--command-config=<clientCommandConfig>] [--config-file=<configFile>]
       [--command-property=<String=String>]... [COMMAND]

Description:

CLI to ease and automate Apache Kafka cluster configuration management.

Options:

      --bootstrap-servers=<bootstrapServer>
                  A list of host/port pairs to use for establishing the initial connection to the Kafka cluster.
      --command-config=<clientCommandConfig>
                  A property file containing configs to be passed to Admin Client.
      --command-property=<String=String>
                  A property file containing configs to be passed to Admin Client.
      --config-file=<configFile>
                  The configuration file.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.

Commands:

  validate  Validate your specification file.
  topics    Apply the Topic changes described by your specs-file against the Kafka cluster you are currently pointing at.
  acls      Apply the ACLs changes described by your specs-file against the Kafka cluster you are currently pointing at.
  brokers   Apply the broker configuration changes described by your specs-file against the Kafka cluster you are currently pointing at.
  quotas    Apply the quotas changes described by your specs-file against the Kafka cluster you are currently pointing at.
  help      Displays help information about the specified command
----

== 🚀 Getting Started

=== The File format

Jikkou uses a common structure for describing the resources/configs to manipulate on your Kafka Cluster (i.e. Topics, ACLs, Quotas, etc).

An empty Jikkou specification file::
[source,yaml]
----
version: 1
metadata:
  labels: {}
  annotations: {}
template:
  vars: {}
specs:
    brokers: {}
    topics: {}
    security:
      users: {}
      roles: {}
----

* `version`: the version of the Jikkou's API (default is `1`).

**Metadata**

* `metadata.labels`: a set of key/value pairs that you can use to describe your specification file (_Note: labels can be referenced in the `specs` sections (a.k.a. templating_).
* `metadata.annotations`: a set of key/value pairs automatically generated by the tool.

**Template**

* `template.vars`: a set of key/value pairs that

**Specs**

* `specs.brokers`: the configuration state of Kafka brokers.
* `specs.security.users`: the description of your ACLs grouped per user (i.e. _principal_).
* `specs.security.roles`: the description of your ACLs roles that you can reference in the `users` section.
* `specs.topics`:  the description of your Kafka Topics.

=== How to use it ?

Jikkou is available:

* As a zip/tar.gz package from https://github.com/streamthoughts/jikkou/releases/tag/v0.6.0[GitHub Releases]
* As a fatJar available from https://repo.maven.apache.org/maven2/io/streamthoughts/jikkou/0.6.0/[Maven Central]
* As a docker image available from https://hub.docker.com/r/streamthoughts/jikkou[Docker Hub].

=== How to Manage Topics ?

Jikkou can be used to create, alter and even delete Kafka topics.

topics-specs.yml::
[source,yaml]
----
version: 1
specs:
    topics:
    - name: "my-topic"
      partitions: 6
      replication_factor: 3
      configs:
        min.insync.replicas: 2
----

Additionally, Jikkou can be used to create, delete or alter topics: ::

[source,bash]
----
$ jikkou --bootstrap-servers localhost:9092 topics create \
--file-path topics-specs.yml \
--set-label topic_prefix=dev- \
--verbose \
--yes
----

(output)

[source]
----
TASK [CREATE] Create a new topic dev-my-topic (partitions=6, replicas=3) - CHANGED **********************
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "dev-my-topic",
    "operation" : "ADD",
    "partitions" : {
      "after" : 6,
      "operation" : "ADD"
    },
    "replication_factor" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

It can be used describe existing topics: ::

[source,bash]
----
$ jikkou --bootstrap-servers localhost:9092 topics describe
----

(output)

[source,yaml]
----
version: 1
metadata:
  annotations:
    generated: "2021-10-10T00:00:00.0Z"
specs:
  brokers: []
  topics:
  - name: "_schemas"
    partitions: 1
    replication_factor: 1
    configs:
      cleanup.policy: "compact"
  - name: "de-my-topic"
    partitions: 12
    replication_factor: 3
    configs:
      min.insync.replicas: "2"
----

=== How to Manage ACLs ?

**Jikkou can be used to describe all ACL policies that need to be created on Kafka Cluster:**

users-specs.yml::
[source,yaml]
----
version: 1
specs:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : 'bench-'
            pattern_type : 'PREFIXED'
          allow_operations : ['READ:*', 'WRITE:*']
        - resource :
            type : 'group'
            pattern : '*'
            pattern_type : 'LITERAL'
          allow_operations : ['DESCRIBE:*']
----

You can also define *roles* to be applied to one or more _principals_.
Jikkou will take care of creating all corresponding ACLs policies.

security-specs.yml::
[source,yaml]
----
version: 1
specs:
  security:
    roles:
    - name: 'AdminTopics'
      permissions:
        - resource:
            type: 'topic'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: ['ALL:*']

    - name: 'AdminGroups'
      permissions:
        - resource:
            type: 'group'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: ['ALL:*']

    users:
      - principal: 'User:admin'
        roles: [ 'AdminTopics', 'AdminGroups' ]

      - principal: 'User:admin-topics'
        roles: [ 'AdminTopics' ]
----

[source,bash]
----
$ jikkou --bootstrap-servers localhost:9092 acls apply \
    --file-path security-specs.yml \
    --verbose \
    --yes
----

(output)
[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:admin-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "admin-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "admin-user",
    "principal" : "User:admin-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL GROUP:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "GROUP",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 146ms
ok : 0, created : 3, altered : 0, deleted : 0 failed : 0
----

As of Kafka 2.0.0, you can use `LITERAL` and `PREFIXED` pattern-type to define new ACLs, then `MATCH` and `ANY` for filtering.

With Jikkou you can use the pattern-type `MATCH` to create ACLs.
This will define ACLs with `LITERAL` pattern type for all topics matching the defined regex.

security-specs.yml::
[source,yaml]
----
version: 1
specs:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : '/bench-[\w-]+/'
            pattern_type : 'MATCH'
          allow_operations : ['READ:*', 'WRITE:*']
----

[source,bash]
----
$ jikkou --bootstrap-servers localhost:9092 \
    acls \
    apply \
    --file-path security-specs.yml \
    --verbose \
    --yes
----

[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:specs to WRITE TOPIC:LITERAL:bench-p1-r3) - CHANGED **********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "WRITE",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:specs to READ TOPIC:LITERAL:bench-p1-r3) - CHANGED ***********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "READ",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
----

=== How to Manage Quotas ?

Jikkou allows you to define the quotas to apply to consumers or producers identified by a client-id or a user principal.

The below example shows you how to set default quotas for all clients, then to override that quotas for a specific client and user.

quotas-specs.yml::
[source,yaml]
----
version: 1
specs:
  quotas:
  - type: CLIENTS_DEFAULT
    configs:
      # quota in percentage (%) of total requests.
      request_byte_rate: 20

  - type: CLIENT
    entity:
      client_id: "producer-client"
    configs:
      # quota in bytes for restricting data production.
      producer_byte_rate: 1000

  - type: USER
    entity:
      user:  "consumer-user"
    configs:
      # quota in bytes for restricting data consumption.
      consumer_byte_rate: 1000
----

Supported quota types are::
* `USERS_DEFAULT`: Set default quotas for all users.
* `USER`: Set quotas for a specific user principal.
* `USER_CLIENT`: Set quotas for a specific user principal and a specific client-id.
* `USER_ALL_CLIENTS`: Set default quotas for a specific user and all clients.
* `CLIENT`: Set default quotas for a specific client.
* `CLIENTS_DEFAULT`: Set default quotas for all clients.

== ConfigMaps

In Jikkou, `ConfigMaps` allows you to define configuration maps
that can be referenced by multiple specs entities (e.g. Topics, Quotas).

topics-specs.yml::
[source,yaml]
----
version: 1
specs:
    config_maps:
    - name: DefaultTopicConfig
      configs:
        log.retention.hours: 72
        min.insync.replicas: 2
    topics:
    - name: "my-first-topic"
      partitions: 6
      replication_factor: 3
      config_map_refs: [ 'DefaultTopicConfig' ]

    - name: "my-second-topic"
      partitions: 12
      replication_factor: 3
      config_map_refs: [ 'DefaultTopicConfig' ]
----

== Templating

Jikkou provides a basic templating mechanism to dynamically set any entity values using https://jinja.palletsprojects.com/en/3.0.x/[Jinja] notation.

Currently, the templating mechanism supports the following scopes::
* `vars`: uses to reference any key/value pairs from the `template.vars` sections or pass through the command arguments.
* `labels`: uses to reference any key/value pairs from the `metadata.labels` sections or pass through the command arguments.
* `system.env`: uses to reference an environment variable.
* `system.props`: uses to reference a system property.

topics-specs.yml::
[source,yaml]
----
version: 1
template:
  vars:
    topic_prefix: "{{ system.env.TOPIC_PREFIX | default('', true) }}"
    default_replication_factor: "{{ system.env.DEFAULT_REPLICATION_FACTOR | default(3, true) }}"
    default_min_insync_replicas: "{{ system.env.DEFAULT_REPLICATION_FACTOR | default(3, true) | int | add(-1) }}"
specs:
    config_maps:
    - name: DefaultTopicConfig
      configs:
        log.retention.hours: 72
        min.insync.replicas: "{{ vars.default_min_insync_replicas }}"
    topics:
    - name: "{{ vars.topic_prefix }}my-first-topic"
      partitions: 6
      replication_factor: "{{ vars.default_replication_factor }}"
      config_map_refs: [ 'DefaultTopicConfig' ]

    - name: "{{ vars.topic_prefix }}my-second-topic"
      partitions: 12
      replication_factor: "{{ vars.default_replication_factor }}"
      config_map_refs: [ 'DefaultTopicConfig' ]
----

NOTE: Jinja templating was introduced to allow you to reuse the same _specs-files_ for multiple target environments.

== Configuration

Internally, Jikkou uses the Java Admin client API for interacting with Kafka.
You can set the configs to be passed to Admin Client using either the command-line arguments `command-config` and `command-property`.

Additionally, Jikkou will lookup for an https://github.com/lightbend/config[HOCON ]file named `application.conf` in the following locations:

* `./application.conf`
* `$HOME/.jikku/application.conf`


reference.conf::
[source, hocon]
----
jikkou {
  adminClient {
    bootstrap.servers = "localhost:9092"
  }
}
----

== 🏭 How to build project ?

You need to have http://www.gradle.org/installation[Gradle] and http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] installed.

=== To build jar

[source,bash]
----
$ ./gradlew jar
----

=== To package distribution

[source,bash]
----
$ ./gradlew distTar
----

=== Build javadoc

[source,bash]
----
$ ./gradlew javadoc
----

=== Cleaning build

[source,bash]
----
$ ./gradlew clean
----

== 💡 Contributions

Any feedback, bug reports and PRs are greatly appreciated!

- **Source Code**: https://github.com/streamthoughts/jikkou
- **Issue Tracker**: https://github.com/streamthoughts/jikkou/issues

== 🙏 Show your support

You think this project can help you or your team to manage your Apache Kafka Cluster ?
Please ⭐ this repository to support us!

== FAQ

== Licence

Copyright 2021 StreamThoughts.

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.See the NOTICE file distributed with this work for additional information regarding copyright ownership.The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions and limitations under the License
