= Jikkou : Automate the management of your Apache Kafka using GitOps approach!

image:https://img.shields.io/github/license/streamthoughts/jikkou[]
image:https://img.shields.io/github/issues/streamthoughts/jikkou[]
image:https://img.shields.io/github/forks/streamthoughts/jikkou[]
image:https://img.shields.io/github/stars/streamthoughts/jikkou[]
image:https://github.com/streamthoughts/jikkou/actions/workflows/maven-build.yml/badge.svg[]

toc::[]

__Note: Jikkou is the project formerly known as **Kafka Specs**. Old versions of this project can still be found under that name.__

**Jikkou** (jikkō / 実行) is a command-line tool to help you automate the management of the configurations that live on your http://kafka.apache.org/[Apache Kafka] clusters.

== Overview

It allows you to define the desired current state of your **Topics**, **ACLs**, or **Quotas**, using one or more YAML resource specification files :

kafka-topics.yml:::
[source,yaml]
----
apiVersion: 1
spec:
  topics:
  - name: 'my-first-topic-with-jikkou'
    partitions: 12
    replication_factor: 3
    configs:
      min.insync.replicas: 2
----

It will then take care of computing and applying the necessary changes directly to your cluster.

[source, bash]
----
$ jikkou --bootstrap-servers localhost:9092 topics apply \
    --file kafka-topics.yml \
    --yes
----

[source]
----
TASK [CREATE] Create a new topic my-first-topic-with-jikkou (partitions=12, replicas=3) - CHANGED **********************
----
[source, json]
----
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "my-first-topic-with-jikkou",
    "operation" : "ADD",
    "partitions" : {
      "after" : 12,
      "operation" : "ADD"
    },
    "replication_factor" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
----
[source]
----
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

Most of the time, you will use Jikkou part of your CI/CD pipeline allowing you to version and ship your Apache Kafka resources directly from Git (more on https://about.gitlab.com/topics/gitops/[GitOps])

Jikkou can be used with self-hosted Kafka, managed Kafka and Confluent Cloud.

NOTE: you can use the environment variable `JIKKOU_DEFAULT_KAFKA_BOOTSTRAP_SERVERS` for connection to the Kafka cluster (instead of the CLI arg `--bootstrap-servers`)

== Why ?

We initially started this project to allow us to quickly and easily (re)create Kafka topics in a declarative way on ephemeral Kafka clusters that we used only for integration testing purposes.

Over time, we began to refactor the solution and extend its functionality to support more production contexts and allow developers and operations teams to share a common tool for working on Kafka.

== Requirements :

1. Kafka 1.0.0 ...
2. Java 17+

_Note: Internally, Jikkou uses the Kafka Java Admin Client API._ Depending on the Kafka Cluster version you use all features may not be supported.

== Installation

Jikkou is available:

* As a zip/tar.gz package from https://github.com/streamthoughts/jikkou/releases/tag/v0.10.0[GitHub Releases]
* As a fatJar available from https://repo.maven.apache.org/maven2/io/streamthoughts/jikkou/0.10.0/[Maven Central]
* As a docker image available from https://hub.docker.com/r/streamthoughts/jikkou[Docker Hub].
* As a Debian package from https://github.com/streamthoughts/jikkou/releases/tag/v0.10.0[GitHub Releases]

```bash
wget https://github.com/streamthoughts/jikkou/releases/download/v0.10.0/jikkou.deb
sudo dpkg -i jikkou.deb
```

NOTE: Jikkou will install itself in the directory :  `/opt/jikkou`

It is recommended to install the bash/zsh completion script `jikkou_completion`:

```bash
wget https://raw.githubusercontent.com/streamthoughts/jikkou/master/jikkou_completion . jikkou_completion
```

or alternatively, run the following command for generation the completion script.

```
source <(jikkou generate-completion)
```

== Jikkou CLI

[source,bash]
----
docker run -it streamthoughts/jikkou:latest --help
Usage:
Jikkou [-hV] [--bootstrap-servers=<bootstrapServer>] [--command-config=<clientCommandConfig>] [--config-file=<configFile>]
       [--command-property=<String=String>]... [COMMAND]

Description:

CLI to ease and automate Apache Kafka cluster configuration management.

Options:

      --bootstrap-servers=<bootstrapServer>
                  A list of host/port pairs to use for establishing the initial connection to the Kafka cluster.
      --command-config=<clientCommandConfig>
                  A property file containing configs to be passed to Admin Client.
      --command-property=<String=String>
                  A property file containing configs to be passed to Admin Client.
      --config-file=<configFile>
                  The configuration file.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.

Commands:

  validate    Validate your specification file.
  topics      Apply the Topic changes described by your specs-file against the Kafka cluster you are currently pointing at.
  acls        Apply the ACLs changes described by your specs-file against the Kafka cluster you are currently pointing at.
  brokers     Apply the broker configuration changes described by your specs-file against the Kafka cluster you are currently pointing at.
  quotas      Apply the quotas changes described by your specs-file against the Kafka cluster you are currently pointing at.
  extensions  List all extensions available.
  config      Sets or retrieves the configuration of this client.
  help        Displays help information about the specified command

See 'Jikkou --help' for more information about a command.
----

== 🚀 User Guide

=== The File format

Jikkou uses a common structure for describing the resources/configs to manipulate on your Kafka Cluster (i.e. Topics, ACLs, Quotas, etc).

An empty Jikkou specification file::
[source,yaml]
----
apiVersion: 1
metadata:
  labels: {}
  annotations: {}
template:
  vars: {}
spec:
    brokers: {}
    topics: {}
    security:
      users: {}
      roles: {}
----

* `version`: the version of the Jikkou's API (default is `1`).

**Metadata**

* `metadata.labels`: a set of key/value pairs that you can use to describe your specification file (_Note: labels can be referenced in the `specs` sections (a.k.a. templating_).
* `metadata.annotations`: a set of key/value pairs automatically generated by the tool.

**Template**

* `template.vars`: a set of key/value pairs that

**Specs**

* `spec.brokers`: the configuration state of Kafka brokers.
* `spec.security.users`: the description of your ACLs grouped per user (i.e. _principal_).
* `spec.security.roles`: the description of your ACLs roles that you can reference in the `users` section.
* `spec.topics`:  the description of your Kafka Topics.

=== How to Manage Topics ?

Jikkou can be used to create, alter and even delete Kafka topics.

kafka-topics.yml::
[source,yaml]
----
apiVersion: 1
spec:
    topics:
    - name: "{{ labels.topic_prefix | default('') }}my-topic"
      partitions: 6
      replication_factor: 3
      configs:
        min.insync.replicas: 2
----

Additionally, Jikkou can be used to create, delete or alter topics: ::

[source,bash]
----
jikkou --bootstrap-servers localhost:9092 topics create \
--files kafka-topics.yml \
--set-label topic_prefix=dev- \
--verbose \
--yes
----

(output)

[source]
----
TASK [CREATE] Create a new topic dev-my-topic (partitions=6, replicas=3) - CHANGED **********************
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "dev-my-topic",
    "operation" : "ADD",
    "partitions" : {
      "after" : 6,
      "operation" : "ADD"
    },
    "replication_factor" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

It can be used describe existing topics: ::

[source,bash]
----
jikkou --bootstrap-servers localhost:9092 topics describe
----

(output)

[source,yaml]
----
apiVersion: 1
metadata:
  annotations:
    generated: "2021-10-10T00:00:00.0Z"
spec:
  brokers: []
  topics:
  - name: "_schemas"
    partitions: 1
    replication_factor: 1
    configs:
      cleanup.policy: "compact"
  - name: "de-my-topic"
    partitions: 12
    replication_factor: 3
    configs:
      min.insync.replicas: "2"
----

=== How to Manage ACLs ?

**Jikkou can be used to describe all ACL policies that need to be created on Kafka Cluster:**

users-specs.yml::
[source,yaml]
----
apiVersion: 1
spec:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : 'bench-'
            pattern_type : 'PREFIXED'
          allow_operations : ['READ:*', 'WRITE:*']
        - resource :
            type : 'group'
            pattern : '*'
            pattern_type : 'LITERAL'
          allow_operations : ['DESCRIBE:*']
----

You can also define *roles* to be applied to one or more _principals_.
Jikkou will take care of creating all corresponding ACLs policies.

kafka-security.yml::
[source,yaml]
----
apiVersion: 1
spec:
  security:
    roles:
    - name: 'AdminTopics'
      permissions:
        - resource:
            type: 'topic'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: ['ALL:*']

    - name: 'AdminGroups'
      permissions:
        - resource:
            type: 'group'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: ['ALL:*']

    users:
      - principal: 'User:admin'
        roles: [ 'AdminTopics', 'AdminGroups' ]

      - principal: 'User:admin-topics'
        roles: [ 'AdminTopics' ]
----

[source,bash]
----
jikkou --bootstrap-servers localhost:9092 acls apply \
    --files kafka-security.yml \
    --verbose \
    --yes
----

(output)
[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:admin-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "admin-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "admin-user",
    "principal" : "User:admin-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL GROUP:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "GROUP",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 146ms
ok : 0, created : 3, altered : 0, deleted : 0 failed : 0
----

As of Kafka 2.0.0, you can use `LITERAL` and `PREFIXED` pattern-type to define new ACLs, then `MATCH` and `ANY` for filtering.

With Jikkou you can use the pattern-type `MATCH` to create ACLs.
This will define ACLs with `LITERAL` pattern type for all topics matching the defined regex.

kafka-security.yml::
[source,yaml]
----
apiVersion: 1
spec:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : '/bench-[\w-]+/'
            pattern_type : 'MATCH'
          allow_operations : ['READ:*', 'WRITE:*']
----

[source,bash]
----
jikkou --bootstrap-servers localhost:9092 \
    acls \
    apply \
    --files kafka-security.yml \
    --verbose \
    --yes
----

[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:specs to WRITE TOPIC:LITERAL:bench-p1-r3) - CHANGED **********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "WRITE",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:specs to READ TOPIC:LITERAL:bench-p1-r3) - CHANGED ***********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "READ",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
----

=== How to Manage Quotas ?

Jikkou allows you to define the quotas to apply to consumers or producers identified by a client-id or a user principal.

The below example shows you how to set default quotas for all clients, then to override that quotas for a specific client and user.

kafka-quotas.yml::
[source,yaml]
----
apiVersion: 1
spec:
  quotas:
  - type: CLIENTS_DEFAULT
    configs:
      # quota in percentage (%) of total requests.
      request_byte_rate: 20

  - type: CLIENT
    entity:
      client_id: "producer-client"
    configs:
      # quota in bytes for restricting data production.
      producer_byte_rate: 1000

  - type: USER
    entity:
      user:  "consumer-user"
    configs:
      # quota in bytes for restricting data consumption.
      consumer_byte_rate: 1000
----

Supported quota types are::
* `USERS_DEFAULT`: Set default quotas for all users.
* `USER`: Set quotas for a specific user principal.
* `USER_CLIENT`: Set quotas for a specific user principal and a specific client-id.
* `USER_ALL_CLIENTS`: Set default quotas for a specific user and all clients.
* `CLIENT`: Set default quotas for a specific client.
* `CLIENTS_DEFAULT`: Set default quotas for all clients.

=== ConfigMaps

In Jikkou, `ConfigMaps` allows you to define configuration maps
that can be referenced by multiple _spec_ entities (e.g. Topics, Quotas).

kafka-topics.yml::
[source,yaml]
----
apiVersion: 1
spec:
    config_maps:
    - name: DefaultTopicConfig
      configs:
        log.retention.hours: 72
        min.insync.replicas: 2
    topics:
    - name: "my-first-topic"
      partitions: 6
      replication_factor: 3
      config_map_refs: [ 'DefaultTopicConfig' ]

    - name: "my-second-topic"
      partitions: 12
      replication_factor: 3
      config_map_refs: [ 'DefaultTopicConfig' ]
----

=== Templating

Jikkou provides a basic templating mechanism to dynamically set any entity values using https://jinja.palletsprojects.com/en/3.0.x/[Jinja] notation.

Currently, the templating mechanism supports the following scopes::
* `vars`: uses to reference any key/value pairs from the `template.vars` sections or pass through the command arguments.
* `labels`: uses to reference any key/value pairs from the `metadata.labels` sections or pass through the command arguments.
* `system.env`: uses to reference an environment variable.
* `system.props`: uses to reference a system property.

kafka-topics.yml::
[source,yaml]
----
apiVersion: 1
template:
  vars:
    topic_prefix: "{{ system.env.TOPIC_PREFIX | default('', true) }}"
    default_replication_factor: "{{ system.env.DEFAULT_REPLICATION_FACTOR | default(3, true) }}"
    default_min_insync_replicas: "{{ system.env.DEFAULT_REPLICATION_FACTOR | default(3, true) | int | add(-1) }}"
spec:
    config_maps:
    - name: DefaultTopicConfig
      configs:
        log.retention.hours: 72
        min.insync.replicas: "{{ vars.default_min_insync_replicas }}"
    topics:
    - name: "{{ vars.topic_prefix }}my-first-topic"
      partitions: 6
      replication_factor: "{{ vars.default_replication_factor }}"
      config_map_refs: [ 'DefaultTopicConfig' ]

    - name: "{{ vars.topic_prefix }}my-second-topic"
      partitions: 12
      replication_factor: "{{ vars.default_replication_factor }}"
      config_map_refs: [ 'DefaultTopicConfig' ]
----

NOTE: Jinja templating was introduced to allow you to reuse the same _resource files_ for multiple target environments.

=== Configuration

Internally, Jikkou uses the Java Admin client API for interacting with Kafka.
You can set the configs to be passed to Admin Client using either the command-line arguments `command-config` and `command-property`.

Additionally, Jikkou will lookup for an https://github.com/lightbend/config[HOCON (Human-Optimized Config Object Notation)] file named `application.conf` in the following locations:

* `./application.conf`
* `$HOME/.jikku/application.conf`


see https://github.com/streamthoughts/jikkou/blob/master/src/main/resources/reference.conf[reference.conf]::
[source, hocon]
----
include::https://github.com/streamthoughts/jikkou/blob/master/src/main/resources/reference.conf[]
----

=== Validating Kafka Resources

Jikkou allows you to run validation rules on declared resources (i.e. _Topics_, _Quotas_, _ACLs_, etc) before executing any action on your Kafka cluster.

To do that, the validations to be applied must be configured in your `application.conf` file as follows:

[source, hocon]
----
jikkou {
    validations = [
        {
          # The fully-qualified name of the Validation class, e.g.:
          type = TopicNameRegexValidation
          # The config values that will be passed to the Validation.
          config = {
            topic-regex = "[a-zA-Z0-9\\._\\-]+"
          }
        }
   ]
}
----

NOTE: The `config` object of a validation will fallback on the top-level Jikkou config.

Jikkou ships with the following built-in _validations_:

[%header,format=csv]
|===
Name, Description, Configs, Class
`TopicMinNumPartitions`, Check if the specified number of partitions for a topic is not less than the minimum required., `topic-min-num-partitions` (default: `1`),`io.streamthoughts.kafka.specs.validations.TopicMinNumPartitionsValidation`
`TopicMinReplicationFactor`, Check if the specified replication factor for a topic is not less than the minimum required., `topic-min-replication-factor` (default: `1`), `io.streamthoughts.kafka.specs.validations.TopicMinReplicationFactorValidation`
`TopicNamePrefix`, Check if the specified name for a topic starts with one of the configured suffixes., `topic-name-prefixes-allowed`, `io.streamthoughts.kafka.specs.validations.TopicNamePrefixValidation`
`TopicNameRegex`, Check if the specified name for a topic matches the configured regex., `topic-name-regex` (default: `"[a-zA-Z0-9\\._\\-]+"`), `io.streamthoughts.kafka.specs.validations.TopicNameRegexValidation`
`TopicNameSuffix`, Check if the specified name for a topic ends with one of the configured suffixes., `topic-name-suffixes-allowed`, `io.streamthoughts.kafka.specs.validations.TopicNameSuffixValidation`
|===

By default, Jikkou is configured with the following _validations_: `TopicMinNumPartitionsValidation`, `TopicMinReplicationFactorValidation`, and `TopicNameRegexValidation`.
You can easily override the config values for those validations by setting the following environment variables:

* `VALIDATION_DEFAULT_TOPIC_NAME_REGEX`
* `VALIDATION_DEFAULT_TOPIC_MIN_NUM_PARTITIONS`
* `VALIDATION_DEFAULT_TOPIC_MIN_REPLICATION_FACTOR`

All validation rule errors are reported in the following form:
[source, text]
----
Validation rule violations:
	- [TopicNameRegex]: Name for topic 'my_topic' does not match the configured regex: [a-zA-Z0-9\.\-]+
	- [TopicMinNumPartitions]: Number of partitions for topic 'my_topic' is less than the minimum required: 1 < 3
	- [TopicMinReplicationFactor]: Replication factor for topic 'my-topic' is less than the minimum required: 1 < 3
----

Additionally, you can implement and configure custom _validations_ by implementing one of the following classes:

* `io.streamthoughts.jikkou.api.validations.Validation`
* `io.streamthoughts.jikkou.api.validations.TopicValidation`
* `io.streamthoughts.jikkou.api.validations.QuotasValidation`

Custom `Validations` should be packaged as an uber JAR and then configured as a Jikkou link:#Extensions[Extension].

=== Transforming Kafka Resources

Jikkou allows you to plug custom transformations on declared resources (i.e. _Topics_, _Quotas_, _ACLs_, etc) before executing any action on your Kafka cluster and before executing validation rules.

To do that, you should implement the `io.streamthoughts.kafka.specs.transforms.Transformation` interface transformations.
Then, transformation must be configured in your `application.conf` file as follows:

[source, hocon]
----
jikkou {
    transformations = [
        {
          # The fully-qualified name of the Transformation class, e.g.:
          type = ...
          # The config values that will be passed to the Transformation.
          config = {}
        }
   ]
}
----

NOTE: The `config` object of a validation will fallback on the top-level Jikkou config.

Custom `Transformations` should be packaged as an uber JAR and then configured as a Jikkou link:#Extensions[Extension].

=== Managing Kafka Resource

Internally, the Jikkou's API defined various `KafkaResourceManager` sub-interfaces for managing each type of Kafka resources

* link:src/main/java/io/streamthoughts/jikkou/api/manager/KafkaTopicManager.java[`KafkaTopicManager`]
* link:src/main/java/io/streamthoughts/jikkou/api/manager/KafkaBrokerManager.java[`KafkaBrokerManager`]
* link:src/main/java/io/streamthoughts/jikkou/api/manager/KafkaAclsManager.java[`KafkaAclsManager`]
* link:src/main/java/io/streamthoughts/jikkou/api/manager/KafkaQuotaManager.java[`KafkaQuotaManager`]

Currently, Jikkou provides built-in implementations for each of these interface based on the Kafka's AdminClient.
Thus, depending on the Kafka service manager you use, you may need to implement custom managers for supporting more features.

Finally, the implementations to be used the Jikkou can be configured directly in your `application.conf` file.

[source, hocon]
----
jikkou {
  # The KafkaResourceManager classes and configurations used for managing kafka resources
  managers {
    kafka {
      brokers {
        type = io.streamthoughts.jikkou.api.manager.kafka.AdminClientKafkaBrokerManager
        config = {}
      }
      topics {
        type = io.streamthoughts.jikkou.api.manager.kafka.AdminClientKafkaTopicManager
        config = {}
      }
      acls {
        type = io.streamthoughts.jikkou.api.manager.kafka.AdminClientKafkaAclsManager
        config = {}
      }
      quotas {
        type = io.streamthoughts.jikkou.api.manager.kafka.AdminClientKafkaQuotasManager
        config = {}
      }
    }
  }
}
----

=== Extensions

Jikkou allows implementing and configuring extensions, i.e., _Validation_ and _Transformer_.

Jikkou sources are available on https://mvnrepository.com/artifact/io.streamthoughts/jikkou[Maven Central]

For Maven::
[source, xml]
----
<dependency>
    <groupId>io.streamthoughts</groupId>
    <artifactId>jikkou</artifactId>
    <version>${jikkou.version}</version>
</dependency>
----

IMPORTANT: The Jikkou API is still evolving. Future releases may introduce minor breaking changes.

For Gradle::
[source]
----
implementation group: 'io.streamthoughts', name: 'jikkou', version: ${jikkou.version}
----

To make your extensions available to Jikkou, install them into one or many local directories.
Then, use the `jikkou.extension.paths` property to configure the list of locations from which the extensions will be loaded.

Each configured directories may contain:

* an uber JAR containing all the classes and third-party dependencies for the extensions.
* a directory containing all JARs for the extensions.

=== Using Jikkou for Integration Tests

Jikkou can also be used for creating all your Kafka Topics for integration test.

Below is a simple code example to illustrate the Jikkou API.

[source,java]
----
@BeforeEach
public void setUp() {
    // (1) Load specification from classpath (e.g. test/resources)
    V1SpecFile specFile = SpecFileLoader.newForYaml().loadFromClasspath("./topics-test.yaml");

    // (2) Create configuration
    var config = JikkouConfig
            .builder()
            .withCLIConfigParams(Map.of("adminClient.bootstrap.servers", getTestingBootstrapServers()))
            .getOrCreate();

    // (3) Process input SpecFile for applying variable resolutions
    // and validating rules.
    var processor = new V1SpecFileProcessor(config);
    specFile = processor.apply(specFile);

    // (4) Create and configure Adminclient-based ClientKafkaTopicManager
    var manager = new AdminClientKafkaTopicManager(config);

    // (5) Create Kafka Topics
    manager.update(
            KafkaResourceManager.UpdateMode.CREATE_ONLY,
            List.of(file.specs()),
            KafkaResourceUpdateContext.with(new TopicChangeOptions(), false)
    );
}
----

== 🏭 Developers

You need to have  http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] and https://www.docker.com/[Docker] installed.

=== Dependencies

**Jikkou modules are built with:**

* Java 17
* https://docs.confluent.io/platform/current/clients/index.html[Apache Kafka Client] (3.0.x)

=== Build project

This project includes https://maven.apache.org/wrapper/[Maven Wrapper].

For building distribution files.

[source,bash]
----
$ ./mvnw clean package -Pdist
----

=== Build Docker Images (locally)

[source,bash]
----
$ make
----

=== Formats

This project uses the Maven plugin https://github.com/diffplug/spotless/tree/master/plugin-maven[Spotless]
to format all Java classes and to apply some code quality checks.

=== Bugs

This project uses the Maven plugin https://spotbugs.github.io/[SpotBugs] and https://find-sec-bugs.github.io/[FindSecBugs]
to run some static analysis to look for bugs in Java code.

Reported bugs can be analysed using SpotBugs GUI:

[source,bash]
----
$ ./mvnw spotbugs:gui
----

== 💡 Contributions

Any feedback, bug reports and PRs are greatly appreciated!

- **Source Code**: https://github.com/streamthoughts/jikkou
- **Issue Tracker**: https://github.com/streamthoughts/jikkou/issues

== 🙏 Show your support

You think this project can help you or your team to manage your Apache Kafka Cluster ?
Please ⭐ this repository to support us!

== FAQ

== Licence

Copyright 2021 StreamThoughts.

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.See the NOTICE file distributed with this work for additional information regarding copyright ownership.The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions and limitations under the License
