= Kafka Specs: Automate the management of your Apache Kafka using GitOps approach!
:toc:
:toc-placement!:

image:https://img.shields.io/github/license/streamthoughts/kafka-specs[]
image:https://img.shields.io/github/issues/streamthoughts/kafka-specs[]
image:https://img.shields.io/github/forks/streamthoughts/kafka-specs[]
image:https://img.shields.io/github/stars/streamthoughts/kafka-specs[]
image:https://circleci.com/gh/streamthoughts/kafka-specs.svg?style=svg[https://circleci.com/gh/streamthoughts/kafka-specs]


toc::[]

http://kafka.apache.org/[Apache Kafka] is a high-throughput, distributed, publish-subscribe messaging system.

**KafkaSpecs** is a java tool to simplify the management of your Kafka Topics and ACLs.

Currently, there are different ways to create/alter topics: ::
- **Automatically** with `auto.create.topics.enable` configured to true (But this not really a good idea in a production or even in non-production environment).
- **Using kafka-topics.sh** - But first you will need a kafka distribution.In addition, this tool need access to zookeeper.
- **Using AdminClient API** - This is a low-level API (the one used by Kafka Specs).

Those solutions are easy to use when starting with Kafka and/or during development cycles.
However, while moving into production you will need more sophisticated tools to automate the creation of your topics.

**KafkaSpecs** allows you to describe your Apache Kafka cluster through a YAML file which is used to create, delete or alter: Topics, ACLs, etc.

**KafkaSpecs** helps you to adopt a GitOps approach to manage Kafka cluster resources.

== Requirements :

1. Kafka 1.0.0 ...
2. Java 11+

== Usages

[source,bash]
----
$ docker run -it streamthoughts/kafka-specs --help
kafka-specs [-hV] [--bootstrap-servers=<bootstrapServer>] [--command-config=<clientCommandConfig>] [--command-property=<String=String>]... [COMMAND]

Description:

CLI to ease and automate Apache Kafka cluster configuration management.

Options:

      --bootstrap-servers=<bootstrapServer>
                  A list of host/port pairs to use for establishing the initial connection to the Kafka cluster.
      --command-config=<clientCommandConfig>
                  A property file containing configs to be passed to Admin Client.
      --command-property=<String=String>
                  A property file containing configs to be passed to Admin Client.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.

Commands:

  validate  Validate your specification file.
  topics    Apply the Topic changes described by your specs-file against the Kafka cluster you are currently pointing at.
  acls      Apply the ACLs changes described by your specs-file against the Kafka cluster you are currently pointing at.
  brokers   Apply the broker configuration changes described by your specs-file against the Kafka cluster you are currently pointing at.
  help      Displays help information about the specified command.
----

== 🚀 Getting Started

=== The File format

Kafka Specs uses a common structure for describing the resources to manipulate on your Kafka Cluster (i.e. Topics, ACLs, etc).

An empty Kafka Specs file::
[source,yaml]
----
version: 1
metadata:
  labels: {}
  annotations: {}
specs:
    brokers: {}
    topics: {}
    security:
      users: {}
      roles: {}
----

* `version`: the version of specs file (default is `1`).
* `metadata.labels`: a set of key/value pairs that you can reference in the `specs` sections (a.k.a. _templating_).
* `metadata.annotations`: a set of key/value pairs automatically generated by the client.
* `specs.brokers`: the configuration state of Kafka brokers.
* `specs.security.users`: the description of your ACLs grouped per user (i.e. _principal_).
* `specs.security.roles`: the description of your ACLs roles that you can reference in the `users` section.
* `specs.topics`:  the description of your Kafka Topics.

=== How to use it ?

Kafka Specs is available:

* As a zip/tar.gz package from https://github.com/streamthoughts/kafka-specs/releases/tag/v0.5.0[GitHub Releases]
* As a fatJar available from https://repo.maven.apache.org/maven2/io/streamthoughts/kafka-specs/0.5.0/[Maven Central]
* As a docker image available from https://hub.docker.com/r/streamthoughts/kafka-specs[Docker Hub].

=== How to Manage Topics ?

Kafka Specs can be used to create, alter and even delete Kafka topics.

kafka-specs-topics.yml::
[source,yaml]
----
version: 1
specs:
    topics:
    - name: "my-topic"
      partitions: 6
      replication_factor: 3
      configs:
        min.insync.replicas: 2
----

Kafka Specs provides a basic templating mechanism to dynamically set any entity values using double curly-brace notation.

Currently, the templating mechanism supports the following scopes:

* `labels`: uses to reference any key/value pairs from the `metadata.labels` sections or pass through the command arguments.
* `system.env`: uses to reference an environment variable.
* `system.props`: uses to reference a system property.

kafka-specs-topics.yml::

[source,yaml]
----
version: 1
metadata:
  labels:
    topic_prefix: ""
    default_replication_factor: 3
specs:
    topics:
    - name: "{{labels.topic_prefix}}my-topic"
      partitions: 6
      replication_factor: {{ labels.default_replication_factor }}
      configs:
        min.insync.replicas: 2
----

Kafka Specs can be used to create, delete or alter topics: ::

[source,bash]
----
$ kafka-specs --bootstrap-servers localhost:9092 \
topics \
create \
--file-path kafka-specs-topics.yml \
--set-label topic_prefix=dev- \
--verbose \
--yes
----

(output)

[source]
----
TASK [CREATE] Create a new topic dev-my-topic (partitions=6, replicas=3) - CHANGED **********************
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "dev-my-topic",
    "operation" : "ADD",
    "partitions" : {
      "after" : 6,
      "operation" : "ADD"
    },
    "replication_factor" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

It can be used describe existing topics: ::

[source,bash]
----
$ kafka-specs --bootstrap-servers localhost:9092 topics describe
----

(output)

[source,yaml]
----
version: 1
metadata:
  annotations:
    generated: "2021-10-10T00:00:00.0Z"
specs:
  brokers: []
  topics:
  - name: "_schemas"
    partitions: 1
    replication_factor: 1
    configs:
      cleanup.policy: "compact"
  - name: "de-my-topic"
    partitions: 12
    replication_factor: 3
    configs:
      min.insync.replicas: "2"
----

=== How to Manage ACLs ?

**Kafka Specs can be used to describe all ACL policies that need to be created on Kafka Cluster:**

kafka-specs-users.yml::
[source,yaml]
----
version: 1
specs:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : 'bench-'
            pattern_type : 'PREFIXED'
          allow_operations : ['READ:*', 'WRITE:*']
        - resource :
            type : 'group'
            pattern : '*'
            pattern_type : 'LITERAL'
          allow_operations : ['DESCRIBE:*']
----

You can also define *roles* to be applied to one or more _principals_.
Kafka Specs will take care of creating all corresponding ACLs policies.

kafka-specs-security.yml::
[source,yaml]
----
version: 1
specs:
  security:
    roles:
    - name: 'AdminTopics'
      resource:
        type: 'topic'
        pattern: '*'
        pattern_type: 'LITERAL'
      allow_operations: ['ALL:*']

    - name: 'AdminGroups'
      resource:
        type: 'group'
        pattern: '*'
        pattern_type: 'LITERAL'
      allow_operations: ['ALL:*']

    users:
      - principal: 'User:admin'
        roles: [ 'AdminTopics', 'AdminGroups' ]

      - principal: 'User:admin-topics'
        roles: [ 'AdminTopics' ]
----

[source,bash]
----
$ kafka-specs --bootstrap-servers localhost:9092 \
    acls \
    apply \
    --file-path kafka-specs-security.yml \
    --verbose \
    --yes
----

(output)
[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:admin-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "admin-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "admin-user",
    "principal" : "User:admin-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL GROUP:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "GROUP",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:kafka-user to ALL TOPIC:LITERAL:*) - CHANGED *****************
{
  "changed" : true,
  "end" : 1633980549689,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "kafka-user",
    "resource_pattern" : "*",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "ALL",
    "permission" : "ALLOW",
    "host" : "*",
    "name" : "kafka-user",
    "principal" : "User:kafka-user"
  },
  "failed" : false,
  "status" : "CHANGED"
}
EXECUTION in 2s 146ms
ok : 0, created : 3, altered : 0, deleted : 0 failed : 0
----

As of Kafka 2.0.0, you can use `LITERAL` and `PREFIXED` pattern-type to define new ACLs, then `MATCH` and `ANY` for filtering.

With Kafka Specs you can use the pattern-type `MATCH` to create ACLs.
This will define ACLs with `LITERAL` pattern type for all topics matching the defined regex.

kafka-specs-security.yml::
[source,yaml]
----
version: 1
specs:
  security:
    users:
    - principal : 'User:benchmark'
      roles  : []
      permissions :
        - resource :
            type : 'topic'
            pattern : '/bench-[\w-]+/'
            pattern_type : 'MATCH'
          allow_operations : ['READ:*', 'WRITE:*']
----

[source,bash]
----
kafka-specs --bootstrap-servers localhost:9092 \
    acls \
    apply \
    --file-path kafka-specs-security.yml \
    --verbose \
    --yes
----

[source]
----
TASK [CREATE] Create a new ACL (ALLOW User:specs to WRITE TOPIC:LITERAL:bench-p1-r3) - CHANGED **********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "WRITE",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
TASK [CREATE] Create a new ACL (ALLOW User:specs to READ TOPIC:LITERAL:bench-p1-r3) - CHANGED ***********
{
  "changed" : true,
  "end" : 1633985047120,
  "resource" : {
    "operation" : "ADD",
    "principal_type" : "User",
    "principal_name" : "specs",
    "resource_pattern" : "bench-p1-r3",
    "pattern_type" : "LITERAL",
    "resource_type" : "TOPIC",
    "operation" : "READ",
    "permission" : "ALLOW",
    "host" : "*",
    "principal" : "User:specs",
    "name" : "specs"
  },
  "failed" : false,
  "status" : "CHANGED"
}
----

== How to build project ?

You need to have http://www.gradle.org/installation[Gradle] and http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] installed.

=== To build jar

[source,bash]
----
$ ./gradlew jar
----

=== To package distribution

[source,bash]
----
$ ./gradlew distTar
----

=== Build javadoc

[source,bash]
----
$ ./gradlew javadoc
----

=== Cleaning build

[source,bash]
----
$ ./gradlew clean
----

== 💡 Contributions

Any feedback, bug reports and PRs are greatly appreciated!

- **Source Code**: https://github.com/streamthoughts/kafka-specs
- **Issue Tracker**: https://github.com/streamthoughts/kafka-specs/issues

== 🙏 Show your support

You think this project can help you or your team to manage your Apache Kafka Cluster ?
Please ⭐ this repository to support us!

== Licence

Copyright 2020 StreamThoughts.

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.See the NOTICE file distributed with this work for additional information regarding copyright ownership.The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions and limitations under the License
