= Jikkou streamlines the management of the configurations that live on your data streams platform!

image:https://img.shields.io/github/license/streamthoughts/jikkou[]
image:https://img.shields.io/github/issues/streamthoughts/jikkou[]
image:https://img.shields.io/github/forks/streamthoughts/jikkou[]
image:https://img.shields.io/github/stars/streamthoughts/jikkou[]
image:https://github.com/streamthoughts/jikkou/actions/workflows/maven-build.yml/badge.svg[]

image:https://sonarcloud.io/api/project_badges/measure?project=streamthoughts_jikkou&metric=reliability_rating[Reliability_rating]
image:https://sonarcloud.io/api/project_badges/measure?project=streamthoughts_jikkou&metric=sqale_rating[Maintainability Rating]
image:https://sonarcloud.io/api/project_badges/measure?project=streamthoughts_jikkou&metric=vulnerabilities[Vulnerabilities]
image:https://sonarcloud.io/api/project_badges/measure?project=streamthoughts_jikkou&metric=coverage[Coverage]

toc::[]

See: https://streamthoughts.github.io/jikkou/[official documentation]

== Introduction

**https://github.com/streamthoughts/jikkou[Jikkou]** (jikkō / 実行) is an open-source tool designed to provide an efficient and easier way to
manage and automate the configurations on your data stream platform.

Developed by Kafka ❤️, Jikkou aims to streamline daily operations on https://kafka.apache.org/documentation/[Apache Kafka],
ensuring that platform governance is no longer a boring and tedious task for both **Developers** and **Administrators**.

Jikkou enables a declarative management approach of **Topics**, **ACLs**, **Quotas**, **Schema** and even more with the use of YAML files called **_Resource Definitions_**.

Taking inspiration from `kubectl` and Kubernetes resource definition files, Jikkou offers an intuitive and user-friendly approach to configuration management.

Jikkou can be used on on-premise Apache Kafka, https://aiven.io/kafka[Aiven], and https://www.confluent.io/confluent-cloud/[Confluent Cloud].

== Motivation

See https://medium.com/@fhussonnois/why-is-managing-kafka-topics-still-such-a-pain-introducing-jikkou-4ee9d5df948[this blog post] for more details.

== The main usage scenarios

* Create new resource entities on an Apache Kafka cluster (i.e., _Topics_, _ACLs_, and _Quotas_).
* Update the configurations of existing resource entities.
* Delete resource entities which are not anymore managed.
* Describe all the configuration defined for Brokers.
* Describe all the configuration defined for _Topics_, _ACLs_, and _Quotas_.
* Replicate configurations of a production cluster to another with a few command lines.
* Initialize a new cluster for testing purpose.

== Core features that make it awesome

* Simple command line interface (CLI) for end user.
* Simple Java API on top of the Kafka's  https://kafka.apache.org/30/javadoc/org/apache/kafka/clients/admin/Admin.html[Java AdminClient].
* Completely stateless and thus does not store any state (Basically: _Your kafka cluster is the state of Jikkou_).
* Pluggable validation rules to ensure that resources meet your requirement before being created or updated ona target cluster.
* Pluggable resource manager to extend Jikkou with cloud managed services for Apache Kafka which are supported out-of-the-box.
* Simple templating mechanism using https://jinja.palletsprojects.com/en/3.0.x/[Jinja] notation.

== Quick Installation

The latest stable release of jikkou (x86) for Linux, and macOScan be downloaded from  https://github.com/streamthoughts/jikkou/releases/tag/v0.25.0[GitHub Releases]

Alternatively, jikkou is also available:

* As a fatJar available from https://repo.maven.apache.org/maven2/io/streamthoughts/jikkou/0.25.0/[Maven Central]
* As a Docker Image available from https://hub.docker.com/r/streamthoughts/jikkou[Docker Hub].

[source, bash]
----
# Download and unzip the latest stable release
RELEASE=jikkou-0.25.0-linux-x86_64.zip
wget https://github.com/streamthoughts/jikkou/releases/download/v0.25.0/$RELEASE && unzip $RELEASE

# Run executable
./jikkou-0.25.0-linux-x86_64/bin/jikkou
----

It is recommended to install the bash/zsh completion script `jikkou_completion`:

[source, bash]
----
wget https://raw.githubusercontent.com/streamthoughts/jikkou/main/jikkou_completion . jikkou_completion
----

or alternatively, run the following command for generation the completion script.

[source, bash]
----
source <(jikkou generate-completion)
----

== Overview

It allows you to define the desired current state of your **Topics**, **ACLs**, or **Quotas**, using one or more YAML resource definition files :

kafka-topics.yml:::
[source,yaml]
----
# file:./kafka-topics.yml
apiVersion: 'kafka.jikkou.io/v1beta2'
kind: 'KafkaTopic'
metadata:
  name: 'my-first-topic-with-jikkou'
  labels: {}
  annotations: {}
spec:
  partitions: 12
  replicas: 3
  configs:
    min.insync.replicas: 2
----

It will then take care of computing and applying the necessary changes directly to your cluster.

[source, bash]
----
$ jikkou apply --files ./kafka-topics.yml
----

[source]
----
TASK [CREATE] Create a new topic my-first-topic-with-jikkou (partitions=12, replicas=3) - CHANGED **********************
----
[source, json]
----
{
  "changed" : true,
  "end" : 1634071489773,
  "resource" : {
    "name" : "my-first-topic-with-jikkou",
    "operation" : "ADD",
    "partitions" : {
      "after" : 12,
      "operation" : "ADD"
    },
    "replicas" : {
      "after" : 3,
      "operation" : "ADD"
    },
    "configs" : {
      "min.insync.replicas" : {
        "after" : "2",
        "operation" : "ADD"
      }
    }
  },
  "failed" : false,
  "status" : "CHANGED"
}
----
[source]
----
EXECUTION in 2s 661ms (DRY_RUN)
ok : 0, created : 1, altered : 0, deleted : 0 failed : 0
----

Most of the time, you will use Jikkou part of your CI/CD pipeline allowing you to version and ship your Apache Kafka resources directly from Git (more on https://about.gitlab.com/topics/gitops/[GitOps])

== Documentation

Check the official https://streamthoughts.github.io/jikkou/[documentation] for further https://streamthoughts.github.io/jikkou/docs/introducion/_installation/[installation] and usage https://streamthoughts.github.io/jikkou/docs/user-guide/[instructions].

== 🏭 Developers

You need to have  http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] and https://www.docker.com/[Docker] installed.

=== Dependencies

Jikkou CLI is built with https://micronaut.io/[Micronaut] and https://picocli.info/[Picocli]

To build the project you will need:

* Java 17
* https://www.graalvm.org/[GraalVM] 22.1.0 or newer to create native executable
* https://testcontainers.com/[TestContainer] to run integration tests

=== Build project

This project includes https://maven.apache.org/wrapper/[Maven Wrapper].

Below are the commands commonly used to build the project:

[source,bash]
----
# Build and run all tests
./mvnw clean verify

# Build and skip integration tests
./mvnw clean verify -DskipTests
----

=== Build Docker Images (locally)

[source,bash]
----
$ make
----

=== Create Native Executable

[source,bash]
----
# Build and run all tests
./mvnw clean verify -Pnative
----

You can then execute the native executable with: `./jikkou-cli/target/jikkou-$PROJECT_VERSION-runner`

=== Create Debian Package (on Linux)

[source,bash]
----
# Build and run all tests
./mvnw clean package -Pnative
./mvnw package -Pdeb
----

You can then install the package with: `sudo dpkg -i ./dist/jikkou-$PROJECT_VERSION-linux-x86_64.deb`

NOTE: Jikkou will install itself in the directory :  `/opt/jikkou`

=== Formats

This project uses the Maven plugin https://github.com/diffplug/spotless/tree/master/plugin-maven[Spotless]
to format all Java classes and to apply some code quality checks.

=== Bugs

This project uses the Maven plugin https://spotbugs.github.io/[SpotBugs] and https://find-sec-bugs.github.io/[FindSecBugs]
to run some static analysis to look for bugs in Java code.

Reported bugs can be analysed using SpotBugs GUI:

[source,bash]
----
$ ./mvnw spotbugs:gui
----

== 💡 Contributions

Any feedback, bug reports and PRs are greatly appreciated!

- **Source Code**: https://github.com/streamthoughts/jikkou
- **Issue Tracker**: https://github.com/streamthoughts/jikkou/issues

== 🙏 Show your support

You think this project can help you or your team to manage your Apache Kafka Cluster ?
Please ⭐ this repository to support us!

== Licence

This code base is available under the Apache License, version 2.