---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaTopic
metadata:
  name: 'my-topic-p3-r1'
  labels: 
    environment: example
spec:
  partitions: 3
  replicas: 1
  configMapRefs:
    - TopicConfig
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaTopic
metadata:
  name: 'my-topic-p4-r1'
  labels:
    environment: example
spec:
  partitions: 4
  replicas: 1
  configMapRefs:
    - TopicConfig
---
apiVersion: "core.jikkou.io/v1beta2"
kind: ConfigMap
metadata:
  name: 'TopicConfig'
data:
    min.insync.replicas: 1
    cleanup.policy: 'delete'
