---
apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'my-topic-p3-r1'
  labels: 
    environment: example
spec:
  partitions: 3
  replicas: 1
  configs:
    min.insync.replicas: 1
    cleanup.policy: 'delete'
---
apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'my-topic-p4-r1'
  labels:
    environment: example
spec:
  partitions: 4
  replicas: 1
  configs:
    min.insync.replicas: 1
    cleanup.policy: 'delete'
