apiVersion: "kafka.jikkou.io/v1"
kind: "KafkaTopicList"
metadata: {}
items:
  - metadata:
      name: 'jikkou-demo-my-first-topic'
    spec:
      partitions: 1
      replicas: 1
      configs:
        cleanup.policy: 'compact'

  - metadata:
      name: 'jikkou-demo-my-second-topic'
    spec:
      partitions: 5
      replicas: 1
      configs:
        cleanup.policy: 'delete'

