apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopicList"
metadata: {}
items:
  - metadata:
      name: 'jikkou-demo-my-first-topic'
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: 'compact'

#  - metadata:
#      name: 'jikkou-demo-my-second-topic'
#    spec:
#      partitions: 5
#      replicationFactor: 1
#      configs:
#       cleanup.policy: 'delete'

