# SPDX-License-Identifier: Apache-2.0
# Copyright (c) The original authors
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#
micronaut:
  application:
    name: jikkou-api-server
  server:
    # Use -1 to run on a random port
    port: 8088

  security:
    enabled: false
#  # Token based authentication configuration
#  authentication: bearer
#  token:
#    enabled: false
#    jwt:
#      signatures:
#        secret:
#          generator:
#            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

# Endpoints configuration
endpoints:
  all:
    port: 8090
    sensitive: false
    enabled: false
  health:
    enabled: true
    details-visible: ANONYMOUS
    # Disable built-in health indicators
    discovery-client.enabled: false
    disk-space.enabled: false

    # Enable Jikkou Health indicators.
    jikkou:
      enabled: true
      timeout-ms: 5000
# Jikkou API Configurations
jikkou:
  #  security:
  #    basic-auth:
  #      - username: "admin"
  #        password: "{noop}admin"

  # The paths from which to load extensions
  extension.paths: []

  # The providers
  providers:
    - name: core
      enabled: true
      type: io.streamthoughts.jikkou.core.CoreExtensionProvider
    # Default configuration for Apache Kafka
    - name: kafka
      enabled: true
      type: io.streamthoughts.jikkou.kafka.KafkaExtensionProvider
      config:
        client:
          bootstrap.servers: localhost:9092
    # Default configuration for Schema Registry
    - name: schemaregistry
      enabled: true
      type: io.streamthoughts.jikkou.schema.registry.SchemaRegistryExtensionProvider
      config:
        url: http://localhost:8081
    # Default configuration for Kafka Connect
    - name: kafkaconnect
      enabled: true
      type: io.streamthoughts.jikkou.kafka.connect.KafkaConnectExtensionProvider
      config:
        clusters:
          - name: localhost
            url: http://localhost:8083

  # The default custom transformations to apply on any resources.
  transformations: [ ]

  # The default custom validations to apply on any resources.
  validations:
    - name: "topicMustHaveValidName"
      type: io.streamthoughts.jikkou.kafka.validation.TopicNameRegexValidation
      priority: 100
      config:
        topicNameRegex: "[a-zA-Z0-9\\._\\-]+"

    - name: "topicMustHavePartitionsEqualsOrGreaterThanOne"
      type: io.streamthoughts.jikkou.kafka.validation.TopicMinNumPartitionsValidation
      priority: 100
      config:
        topicMinNumPartitions: 1

    - name: "topicMustHaveReplicasEqualsOrGreaterThanOne"
      type: io.streamthoughts.jikkou.kafka.validation.TopicMinReplicationFactorValidation
      priority: 100
      config:
        topicMinReplicationFactor: 1

#  # The default custom reporters to report applied changes.
#  reporters:
#    # Uncomment following lines to enable default kafka reporter
#    - name: "default"
#      type: io.streamthoughts.jikkou.kafka.reporter.KafkaChangeReporter
#      config:
#        event.source: "jikkou/cli"
#        kafka:
#          topic.creation.enabled: true
#          topic.creation.defaultReplicationFactor: 1
#          topic.name: "jikkou-resource-change-event"
#          client: ${jikkou.kafka.client}
#          client.id:  "jikkou-reporter-producer"