apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaAuthorizationList
metadata:
  labels: { }
spec:
  roles:
    - name: 'AdminTopics'
      permissions:
        - resource:
            type: 'topic'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: [ 'ALL:*' ]

    - name: 'AdminGroups'
      permissions:
        - resource:
            type: 'group'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: [ 'ALL:*' ]

    - name: 'ReadWriteTopicsMatchingBench'
      permissions:
        - resource:
            type: 'topic'
            pattern: '/^bench-([.-])*$/'
            pattern_type: 'MATCH'
          allow_operations: [ 'READ:*', 'WRITE:*' ]
  users:
    - principal: 'User:kafka'
      roles: [ 'AdminTopics', 'AdminGroups' ]

    - principal: 'User:benchmark'
      roles: [ ]
      permissions:
        - resource:
            type: 'topic'
            pattern: 'bench-'
            pattern_type: 'PREFIXED'
          allow_operations: [ 'READ:*', 'WRITE:*' ]
        - resource:
            type: 'group'
            pattern: '*'
            pattern_type: 'LITERAL'
          allow_operations: [ 'DESCRIBE:*' ]