apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaTopicList
metadata:
  annotations: {}
  labels: {}
items:
  - metadata:
      name: "topic-test-A"
    spec:
      partitions: 3
      replicas: 1
      configs:
        cleanup.policy: compact

  - metadata:
      name: "topic-test-B"
    spec:
      partitions: 3
      replicas: 1
      configs:
        cleanup.policy: delete

  - metadata:
      name: "topic-test-C"
      annotations:
        jikkou.io/delete: true
    spec: {}
