jikkou {
  # Apache Kafka Provider (SASL_PLAINTEXT)
  provider.kafka {
    enabled = true
    type = io.jikkou.kafka.KafkaExtensionProvider
    default = true
    config = {
      client {
        bootstrap.servers = "localhost:9093"
        security.protocol = "SASL_PLAINTEXT"
        sasl.mechanism = "PLAIN"
        sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\";"
      }
      brokers {
        waitForEnabled = true
        waitForMinAvailable = 1
        waitForTimeoutMs = 60000
      }
    }
  }
}
