Args = --initialize-at-build-time=org.apache.hadoop.util.PlatformName \
       --initialize-at-build-time=org.apache.hadoop.util.VersionInfo \
       --initialize-at-build-time=org.apache.hadoop.util.NativeCodeLoader
